### ISSUE TITLE
Index thread safety

### ISSUE THREAD

**Issue by Dr-Champ** [nmslib/hnsw#29]
Hi,

First of all, thanks for sharing with us such a nice work of yours. It really makes my work that much easier with an efficient and fast search algorithm like this. 

A question on thread safety of the hnswlib.Index() object though, as I couldn't find it mentioned explicitly anywhere in the wiki. Is the index object thread safe and can be shared between threads? I'm thinking about having multiple threads sharing this object and call its knn_query() independently.

Thanks

**Comment by sumsuddin** [comment]
My experience is, you can search from multiple threads but I think I had issues when I added for indexing using multiple threads.

**Comment by yurymalkov** [comment]
Hi,
I have checked it only for C++, but parallel searches should be ok and parallel insertions should also be ok. However mixing searches and insertions can cause segfault. 
This is done intentionally to get the best performance during search. However, if needed, locks can be added (i.e. as a separate thread safe method method).

**Comment by Dr-Champ** [comment]
Thanks. Being thread safe for parallel searches is good enough for my use case.   :)
