### ISSUE TITLE
command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by pawmis** [nmslib/hnsw#40]
from hnsw/python_bindings/
=> python setup.py install

running install
running bdist_egg
running egg_info
writing nmslib.egg-info/PKG-INFO
writing dependency_links to nmslib.egg-info/dependency_links.txt
writing requirements to nmslib.egg-info/requires.txt
writing top-level names to nmslib.egg-info/top_level.txt
reading manifest file 'nmslib.egg-info/SOURCES.txt'
writing manifest file 'nmslib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
gcc -pthread -B /home/thepride99/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/thepride99/anaconda3/include/python3.6m -c /tmp/tmp663kadko.cpp -o tmp/tmp663kadko.o -std=c++14
gcc: error: unrecognized command line option ‘-std=c++14’
gcc -pthread -B /home/thepride99/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/thepride99/anaconda3/include/python3.6m -c /tmp/tmptfty6n9i.cpp -o tmp/tmptfty6n9i.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -B /home/thepride99/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/thepride99/anaconda3/include/python3.6m -c /tmp/tmpkk_m2rzy.cpp -o tmp/tmpkk_m2rzy.o -fvisibility=hidden
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
building 'nmslib' extension
gcc -pthread -B /home/thepride99/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./nmslib/similarity_search/include -I/home/thepride99/anaconda3/include/python3.6m -I/home/thepride99/.local/include/python3.6m -I/home/thepride99/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/thepride99/anaconda3/include/python3.6m -c nmslib.cc -o build/temp.linux-x86_64-3.6/nmslib.o -O3 -march=native -fopenmp -DVERSION_INFO="1.7.3.2" -std=c++11 -fvisibility=hidden
gcc: error: nmslib.cc: No such file or directory
error: command 'gcc' failed with exit status 1

**Comment by yurymalkov** [comment]
@pawmis Hi, are you sure you've made a fresh clone? 
Judging but the errors it seems like you are installing nmslib, not hnswlib.

**Comment by pawmis** [comment]
I got this a similar error of exit status 1 for hnswlib as well. I solved it by installing latest gcc compiler. 
Thanks for response!

**Comment by HarryCaveMan** [comment]
I am having this issue even with gcc7.2 which should be fine with `-std=c++14` flag

**Comment by ninjachen** [comment]
I have met the same issue, and fix it by following steps:

- sudo yum -y install gcc
- sudo yum -y install gcc-c++
- sudo yum install python3-devel  
- pip install hnswlib

Tested on centos
