### ISSUE TITLE
Problem when running hnswlib on ARM demoboard

### ISSUE THREAD

**Issue by AmigoCDT** [nmslib/hnsw#44]
Thank you for the great work.
For my project, I need to run hnswlib on a ARM demoboard, but this get problem. I think it is caused by #include <x86intrin.h> in space_ip.h, in this code, use SSE to get less computing time. 
Is there any better way rather than change to use NEON Instruction set to solve this problem?
Looking forward for you reply. thank you so much.

**Comment by yurymalkov** [comment]
@AmigoCDT thank you!
I see at least two other options here:
1) making a designated space with calls to neon blas libraries (L2 distance can be computed via dot product).
2) using compiler auto-vectorization. Not sure of it is as easy as it sounds for free compilers, but probably should be doable.

**Comment by AmigoCDT** [comment]
@yurymalkov 
Thanks so much, I use first to solve this problem. use the NEON to compute inner product.
Thank you and thanks for the great project.

**Comment by yurymalkov** [comment]
@AmigoCDT Great! Glad it helps.
