### ISSUE TITLE
duplicated codes with previous 3 lines

### ISSUE THREAD

**Issue by ironyoung** [nmslib/hnsw#52]
https://github.com/nmslib/hnsw/blob/48a5980e5a4facdba749bde7352652b2deda5371/hnswlib/brutoforce.h#L121

**Comment by ironyoung** [comment]
thank u for your reply. I can't push my branch to this hnsw. Do I have permission ?

**Comment by ironyoung** [comment]
thank u for your reply! I have a new pull request, please review it: https://github.com/nmslib/hnsw/pull/53

**Comment by yurymalkov** [comment]
Thanks!
