### ISSUE TITLE
Is it possible to query only with selected elements of the vector?

### ISSUE THREAD

**Issue by robclouth** [nmslib/hnsw#60]
For example, find items similar to the the first n elements of the vector, ignoring the others.

Thanks!

**Comment by yurymalkov** [comment]
Yes, it is possible and should work (to some extent).

You can do it with the C++ interface by defining a new space, which has a switch for changing the effective vector length. Or, alternatively, just alter *dist_func_param_ (which is the dimensionality of the L2 and cosine spaces passed to distance function) between the insertions and queries.

**Comment by robclouth** [comment]
Thanks for the suggestion!
