### ISSUE TITLE
Intel E5-2680 coredump

### ISSUE THREAD

**Issue by coleca** [nmslib/hnsw#61]
We're having an issue w/the library core dumping on certain Intel processors, specifically the Intel E5-2680 v2 @ 2.80 GHz.

Steps to reproduce:

```
# python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hnswlib
>>> p = hnswlib.Index(space='l2', dim=128)
Illegal instruction (core dumped)
#
```

If you run it on an AWS c3 instance it will fail.  On other instance types with the newer Intel E5-2686 v4 @ 2.30 GHz processor it works fine, for example on a m4 or i3 instance type.

Any ideas?  The 2680 doesn't have the AVX instruction set. 

I have a Docker image you can use to check it as well:

`docker run -it quay.io/kairosinc/cpubug-test:latest`

Thanks!

**Comment by yurymalkov** [comment]
Hi @coleca,
Do you build hnswlib on the target machine? 
This issue seems to be related to #17.

**Comment by coleca** [comment]
That must be it because we build via Jenkins on a host that has AVX.  No way to compile in both, but determine which one to use at runtime?  

Is there a big impact for running the non-AVX version on an AVX enabled host?  

Easiest solution will probably be for us to remove the non-AVX hosts from our cluster going forward.  

Thanks for your help!

**Comment by yurymalkov** [comment]
@coleca There is a way to determine that and make different paths for different architectures.
The impact depends on the size of the vector. E.g. for 128-dimensional vectors it is ~10-15%. For larger vectors it is higher.

**Comment by coleca** [comment]
Great, thanks again!
