### ISSUE TITLE
Duplicate labels permitted?

### ISSUE THREAD

**Issue by SeanU** [nmslib/hnsw#62]
`HierarchicalNSW` will allow you to add two different vectors with the same label, which seems slightly surprising to me.

I'm not sure what to suggest here, since I don't know what the intended behavior is; I just wanted to bring it up.  For my purposes, I might prefer the ability to overwrite the old value. I realize that may not suit everyone's needs, though. I presume it would depend on issue #4, too.

**Comment by yurymalkov** [comment]
Hi @SeanU, initially the labels where allowed to be duplicated (e.g. so that they can be used as classed for kNN classification), but after #57 is merged the labels will be required to be unique.

After the deletion will be added you would be able to overwrite old elements.

**Comment by SeanU** [comment]
Hmm. That's a good point about making it more directly usable for KNN classification, though.

That said, if losing that feature is the cost of #57, maybe it's a net gain. It would be cheaper to maintain a map from labels to classes than it is to maintain a 2nd copy of all the vectors in memory for use cases like K-means clustering.
