### ISSUE TITLE
Is it possible to build hnsw on the top of spark graph?

### ISSUE THREAD

**Issue by hiyijian** [nmslib/hnsw#69]
Dear stuff,
   Any comments or experience?

**Comment by searchivarius** [comment]
@hiyijian Which Spark graph do you mean?
 FIY stuff means something different from what you meant :-)

**Comment by hiyijian** [comment]
Thanks @searchivarius . Things such as [GraphFrame](http://graphframes.github.io/) or so. I am not expert at spark. Just want to push hnsw to much larger scale.

**Comment by searchivarius** [comment]
@hiyijian for retrieval purposes sharding is typically a much better solution that building the gigantic graph (which is likely to be a very slow process).

**Comment by hiyijian** [comment]
@searchivarius Thanks
