### ISSUE TITLE
L2Space distance is sorted from big to small

### ISSUE THREAD

**Issue by willard-yuan** [nmslib/hnsw#7]
@yurymalkov Hi, yurymalkov. I'm using the hnsw to retrieve rootsift, and the distance is L2Space. I find the distances is not sorted from small to big, but sorted from big to small. I'm not sure I use it right. The code is as follows:

```c++
cv::Ptr<cv::Feature2D> detector = cv::xfeatures2d::SIFT::create();
cv::Mat im = cv::imread("123.jpg", 1);
if (im.empty()) return 0;

std::vector<cv::KeyPoint> keypoints;
cv::Mat img_descs;
detector->detect(im, keypoints);
detector->compute(im, keypoints, img_descs);

if (keypoints.size() < 5) {
    std::cout << "too few feature points: " << std::endl;
    return 0;
}

rootSift(img_descs);

for(int i = 0; i < img_descs.rows; i++) {
    
    for(int j = 0; j < vecdim; j++) {
        massb[j] = img_descs.at<float>(i, j);
    }
    std::priority_queue<std::pair<float, labeltype >> candidates = appr_alg->searchKnn(massb, 10);
    
    for(int k = 0; k < totalNum; k++) {
        if(candidates.top().first < 0.25 &&  abs(keypoints.at(i).angle - geosInfo.at(candidates.top().second).Pt.angle) < 10){
            cout << geosInfo.at(candidates.top().second).fileBaseName << ", angle diff: " << abs(keypoints.at(i).angle - geosInfo.at(candidates.top().second).Pt.angle) << ", dist: " << candidates.top().first << endl;
        }
        candidates.pop();
    }
}
```

To sort distance from small to big, a stupid way is set K in `appr_alg->searchKnn(massb, K)` to database size. Would you tell me how to solve it gracefully？

**Comment by yurymalkov** [comment]
Hi @willard-yuan,

Yes, it seems to be a strange design choice... I'll fix it this week.

To convert the order you can use a separate array (and filling it backwards) or a priority queue with reverse ordering. Should be quite easy and fast at runtime.

As another temporary workaround you can change the ordering inside the lib code by adding 'minus' before the distance in the line 
https://github.com/nmslib/hnsw/blob/master/hnswlib/hnswalg.h#L718 , i.e.
```results.push(std::pair<dist_t, labeltype>(-rez.first, getExternalLabel(rez.second)));```
This would lead to returning the closest items first (as desired), but you would need to negate the distances in your code if you want them to be positive.

**Comment by willard-yuan** [comment]
Hi @yurymalkov ,

The inner product distance seems also faced the problem. I have tried the method by replacing the [hnswalg.h#L718](https://github.com/nmslib/hnsw/blob/master/hnswlib/hnswalg.h#L718) with `results.push(std::pair<dist_t, labeltype>(-rez.first, getExternalLabel(rez.second)));`, but the search becomes very slowly. Hoping to fix the problem soon.

**Comment by yurymalkov** [comment]
Hi @willard-yuan,
This is strange. The replacement should not have any effect on the performance.
Anyway, sure, soon I'll fix the output order.

**Comment by willard-yuan** [comment]
@yurymalkov Hi, it's my error. I'm very sorry to disturb you.

**Comment by yurymalkov** [comment]
@willard-yuan Are you still need this?
I have noticed that nmslib use the same (inverse) order of output, so probably, nmslib users maybe be confused if the order is changed.

**Comment by willard-yuan** [comment]
@yurymalkov I don't need it. Thanks.

**Comment by yurymalkov** [comment]
Ok. Cool! So I am closing the issue.
